# https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-logging.html
logging:
  level:
    root: INFO
    com.stratio: DEBUG
#server:
#  contextPath : /myWebApp
spring:
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#
# https://drissamri.be/blog/java/enable-https-in-spring-boot/
#
# ?> keytool -genkey -alias tomcat -storetype PKCS12 -keyalg RSA -keysize 2048 -keystore keystore.p12 -validity 3650
#
server:
  port: 8443
  ssl:
    key-store: keystore.p12
    key-store-password: changeit
    keyStoreType: PKCS12
    keyAlias: tomcat
